// <auto-generated />
namespace CadnunsDev.AngularECommerce.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration_inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201607240403431_migration_inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
